#!/bin/bash

tee $MESON_BUILD_ROOT/toolchain.cmake << EOF
set(CMAKE_SYSTEM_NAME $1)
set(CMAKE_SYSTEM_PROCESSOR $2)

set(CMAKE_C_COMPILER $3)
set(CMAKE_CXX_COMPILER $4)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF

if [ -n "$5" ]; then
    cat >> $MESON_BUILD_ROOT/toolchain.cmake << EOF
set(CMAKE_SYSROOT $5)
set(CMAKE_FIND_ROOT_PATH $5)
EOF
fi